### ISSUE TITLE
Render architecture for different types of input data

### ISSUE THREAD

**Issue by martinschorb** [saalfeldlab/render#106]
Hi,

we are making progress in establishing a Render-based stitching and alignment infrastructure for volume EM data at our institute.

Before populating the server with data, we are discussing the strategy to discriminate the different types of datasets (FIB-SEM vs. SBSEM vs. ssTEM,...)

we thought about the following options:

1. a tag comparable to `owner` but describing the data set type
2. running separate Render instances for different types of data

How complicated would it be to introduce another level of tag for dataset type?
What would you suggest? Maybe there are other options...

**Comment by trautmane** [comment]
Hi Martin,

At Janelia, we don't explicitly store EM type anywhere.  I suppose you could say we use the stack owner and project fields as proxies for that information since each project contains data acquired using a particular technique.  So far, having two levels (owner + project) of categorization has been sufficient for our needs.  

Here are a couple of examples of our current setup:

The flyTEM stacks are all ssTEM data.  My original thought when setting this up was to have owners as labs and then have projects for each sample.  Over time, we realized it was more useful to have each sample be an owner (see next example of FIB-SEM data) and then have projects for either different pieces of the sample or for different reconstruction efforts.
  
<img width="1412" alt="Screen Shot 2020-09-29 at 7 37 26 AM" src="https://user-images.githubusercontent.com/4457104/94553723-f194b680-0226-11eb-9eee-76d55e4ea845.png">

The Z1217_19m stacks are all FIB-SEM data from a single sample (fly VNC in this case) with each project containing a tab (3D sub-volume) of that sample.

<img width="1416" alt="Screen Shot 2020-09-29 at 7 38 32 AM" src="https://user-images.githubusercontent.com/4457104/94555699-f73fcb80-0229-11eb-878a-2f4e6e55e62e.png">

You mentioned running separate Render instances for different types of data (or different projects), which is something we've thought we might want to or need to do.  We have yet to do that though, since our large single instance has been fine with current usage patterns.  In my mind, the key driver for splitting into multiple instances would be load / usage rather than data type - but you could choose to split things up for any reason.

All of that being said, it would be fairly simple to add another field (or list of tags/labels) to the persisted stack metadata.  

Let me know if you think that is necessary,
Eric

**Comment by martinschorb** [comment]
Hi Eric,

Thanks for you explanation.
That makes sense. I was wonder how tightly your interpretation of this `owner`/`project` nomenclature would be. I guess, we can find some convention to start with as it is now.
